### PR TITLE
Fixed warnings and power rule

### LINKED ISSUE #66: Ambiguity error with power of a variable
```jl
julia> t = IndependentVariable(:t)
IndependentVariable(t)

julia> t^4
ERROR: MethodError: ^(::ModelingToolkit.Variable, ::Int64) is ambiguous. Candidates:
  ^(x::ModelingToolkit.Expression, y::Number) in ModelingToolkit at /Users/dpsanders/.julia/v0.6/MacroTools/src/utils.jl:260
  ^(x::Number, p::Integer) in Base at intfuncs.jl:198
Possible fix, define
  ^(::ModelingToolkit.Expression, ::Integer)
Stacktrace:
 [1] literal_pow(::Base.#^, ::ModelingToolkit.Variable, ::Type{Val{4}}) at ./intfuncs.jl:208
```

### PR DESCRIPTION
**Pull request by chakravala**
resolves #66 and #65

### CODE REVIEW

File: src/function_registration.jl [hunk 1]
```diff
@@ -41,11 +41,14 @@ for (M, f, arity) in DiffRules.diffrules()
...
     basefun = Expr(:., Base, QuoteNode(fun))
     sig = :($basefun(x,y))
     @eval @register $sig
 end
 
 # ifelse
 @register Base.ifelse(cond,t,f)
+
+# special cases
+Base.:^(x::Expression,y::T) where T <: Integer = Operation(Base.:^, Expression[x, y])
```
Comment (ChrisRackauckas) [inline src/function_registration.jl]: oh I see. Yeah, the quick fix is to just special case the operators against literals. Do Integer and AbstractFloat. Are things like `O + 3` and stuff already handled?

File: src/function_registration.jl [hunk 2]
```diff
@@ -41,11 +41,14 @@ for (M, f, arity) in DiffRules.diffrules()
     @eval @register $sig
 end
 
-for fun = (:<, :>, :(==), :~, :!, :&, :|, :div, :max, :min)
```
[the remark this answers is not in the document]
Comment (chakravala) [reply src/function_registration.jl]: the warnings were caused because these are extra definitions not needed. the functionality already works without it being defined here, don't ask me why though, since I havent figured out why that is yet.

File: src/function_registration.jl (hunk 1 above)
Comment (chakravala) [reply src/function_registration.jl]: What is `O` here? a variable? It is not necessary to make one for `AbstractFloat`, all that is needed is `Integer`, this is a peculiarity with the `Base.:^` method.

Comment (ChrisRackauckas) [reply src/function_registration.jl]: Does `O^2.5` work already? `O` is just some `Expression`.

Comment (chakravala) [reply src/function_registration.jl]: Yes, that already works, the `Integer` method issue is an artifact due to raising matrices to integer powers in `Base`, I believe, so it is only necessary to add a special method for that. All the other extra methods in `Reduce` I needed to create were all for matrices.

File: src/function_registration.jl (hunk 2 above)
[the remark this answers is not in the document]
Comment (chakravala) [reply src/function_registration.jl]: plus, the way it was defined here, the `max` and `min` method would be defined as Binary operators, when it is actually n-ary, so it wasn't a good definition anyway.
